# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Human Behavior Project
email: kai.larsen@colorado.edu
description: >- # this means to ignore newlines until "baseurl:"
    The Human Behavior Project (HBP) aims to integrate the behavioral sciences through natural language processing algorithms. 
    The project is predicated on what we term the Reverse Progress Problem of the Behavioral Sciences, and accomplished through 
    the production of the Internomological Network Search Engine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: humanbehaviorproject
twitter_username: HBP_CUBoulder

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - scripts/
    - get-blog.py

collections:
    people:
        output: true
        permalink: /people/:name
    
    friends_of_the_project:
        output: true
        type: "Friend of the project"
        permalink: /people/:name
    
    faculty_affiliates_and_collaborators:
        output: true
        type: "Faculty affiliate and collaborator"
        permalink: /people/:name
        layout: "person"
        
    phd_students:
        output: true
        type: "PhD Student"
        permalink: /people/:name
        layout: "person"
        
    phd_graduates:
        output: true
        type: "PhD Graduate"
        permalink: /people/:name
        layout: "person"
        
    research_assistants_current:
        output: true
        type: "Current Research Assistant"
        permalink: /people/:name
        layout: "person"
        
    research_assistants_former:
        output: true
        type: "Former Research Assistant"
        permalink: /people/:name
        layout: "person"

defaults:
    - scope:
            path: ""
      values:
            layout: "default"
            
    -   scope:
            path: ""
            type: posts
        values:
            layout: "post"
        
    
    - scope:
            path: "assets/papers"
      values:
            paper: true
    
    - scope:
            path: ""
            type: "people"
      values:
            layout: "person"
            
    - scope:
            path: ""
            type: research_assistants_current
      values:
            layout: "person"
            
    - scope:
            path: ""
            type: research_assistants_former
      values:
            layout: "person"
    
    - scope:
            path: "_people/research-assistants"
            type: "people"
      values:
            job_title: "Research Assistant"

host: 0.0.0.0

google_analytics: UA-15172164-4

header_pages:
    - index.md
    - contributors.md
    - funders.md
    - news.md
    - available_positions.md
    - resources.md
